
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.1"
  
[[constraint]]
  name = "github.com/ZB-io/zbio"
  version = "0.0.6"
  
[prune]
  go-tests = true
  unused-packages = true

